//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Muestreos.ServicioRef_WebService_BD {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioRef_WebService_BD.WS_Base_DatosSoap")]
    public interface WS_Base_DatosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarCredenciales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VerificarCredenciales(string pA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarCredenciales", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> VerificarCredencialesAsync(string pA);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_Base_DatosSoapChannel : Sistema_Muestreos.ServicioRef_WebService_BD.WS_Base_DatosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_Base_DatosSoapClient : System.ServiceModel.ClientBase<Sistema_Muestreos.ServicioRef_WebService_BD.WS_Base_DatosSoap>, Sistema_Muestreos.ServicioRef_WebService_BD.WS_Base_DatosSoap {
        
        public WS_Base_DatosSoapClient() {
        }
        
        public WS_Base_DatosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_Base_DatosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_Base_DatosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_Base_DatosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet VerificarCredenciales(string pA) {
            return base.Channel.VerificarCredenciales(pA);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> VerificarCredencialesAsync(string pA) {
            return base.Channel.VerificarCredencialesAsync(pA);
        }
    }
}
